rvm:
  - 1.9.3
env:
  - DB=postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
